---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2
    driver:
#      gui: true
      box: opentable/win-2012r2-standard-amd64-nocm
      network:
        - ["forwarded_port", {guest: 389, host: 8389}]
        - ["forwarded_port", {guest: 636, host: 8636}]

suites:
  - name: default
    run_list:
      - recipe[chef-server-ldap-host::default]
    attributes:
