---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2
    driver:
#      gui: true
      box: opentable/win-2012r2-standard-amd64-nocm
      guest: windows
      network:
        - ["forwarded_port", {guest: 389, host: 8389, auto_correct: true}]
        - ["forwarded_port", {guest: 636, host: 8636, auto_correct: true}]
        - ["private_network", {ip: "192.168.34.100"}]

suites:
  - name: default
    run_list:
      - recipe[chef-server-ldap-host::default]
    attributes:
